# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Downloads\Video_Play\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 580)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.0170455, x2:0.5, y2:1, stop:0 rgba(134, 136, 134, 255), stop:1 rgba(178, 200, 225, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Video = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Video.setGeometry(QtCore.QRect(5, 5, 790, 450))
        self.groupBox_Video.setStyleSheet("QGroupBox\n"
"{\n"
"    border:1px solid black;\n"
"}")
        self.groupBox_Video.setTitle("")
        self.groupBox_Video.setObjectName("groupBox_Video")
        self.pushButton_Play_Pause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Play_Pause.setGeometry(QtCore.QRect(70, 500, 51, 41))
        self.pushButton_Play_Pause.setAutoFillBackground(False)
        self.pushButton_Play_Pause.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 255);\n"
"}")
        self.pushButton_Play_Pause.setObjectName("pushButton_Play_Pause")
        self.pushButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Stop.setGeometry(QtCore.QRect(130, 500, 51, 41))
        self.pushButton_Stop.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 255);\n"
"}")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_Volume = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Volume.setGeometry(QtCore.QRect(590, 500, 61, 41))
        self.pushButton_Volume.setStyleSheet("QPushButton{\n"
"    background-color:rgb(170, 0, 255);\n"
"}")
        self.pushButton_Volume.setObjectName("pushButton_Volume")
        self.horizontalSlider_Volume = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_Volume.setGeometry(QtCore.QRect(660, 510, 131, 22))
        self.horizontalSlider_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Volume.setObjectName("horizontalSlider_Volume")
        self.horizontalSlider_Duration = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_Duration.setGeometry(QtCore.QRect(130, 460, 551, 22))
        self.horizontalSlider_Duration.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Duration.setObjectName("horizontalSlider_Duration")
        self.label_current_Time = QtWidgets.QLabel(self.centralwidget)
        self.label_current_Time.setGeometry(QtCore.QRect(360, 480, 91, 16))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_current_Time.setFont(font)
        self.label_current_Time.setStyleSheet("")
        self.label_current_Time.setObjectName("label_current_Time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 26))
        self.menubar.setObjectName("menubar")
        self.menuSelect_Video_File = QtWidgets.QMenu(self.menubar)
        self.menuSelect_Video_File.setObjectName("menuSelect_Video_File")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuSelect_Video_File.addAction(self.actionOpen)
        self.menubar.addAction(self.menuSelect_Video_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Play_Pause.setText(_translate("MainWindow", "Play"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Volume.setText(_translate("MainWindow", "Volume"))
        self.label_current_Time.setText(_translate("MainWindow", "00:00:00"))
        self.menuSelect_Video_File.setTitle(_translate("MainWindow", "Select Video File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
